---
layout: product
type: issue backgrounder
title: Summer Meal sites in 2014
summary: |
  Discover where summer meal sites were located in 2014.
media:
  map: https://www.google.com/fusiontables/DataSource?docid=1rMd2bno7LOhbjNAgGpDbMRr2ecJFNyMN3UOXJKPq
date: 2014-09-14
categories:
  - Summer Meals
featured: true
---
A map of the 2014 summer meal sites. Click on the red pin points to get the site name and operating hours. 
